# Generated by Django 6.0.3 on 2026-06-02 15:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('tenant', models.CharField(db_index=True, default='default', max_length=100)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('engine_version', models.CharField(default='1.0.0', max_length=50)),
                ('drug_db_version', models.CharField(default='1.0.0', max_length=50)),
                ('input_state', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('reasoning_chain', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'absorb_audit_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_key', models.CharField(max_length=100, unique=True)),
                ('tenant', models.CharField(db_index=True, default='default', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('age', models.FloatField(default=45)),
                ('weight', models.FloatField(default=70)),
                ('height', models.FloatField(default=170)),
                ('sex', models.CharField(default='M', max_length=1)),
                ('serum_creatinine', models.FloatField(default=1.0)),
                ('child_pugh_score', models.IntegerField(default=5)),
                ('body_fat_pct', models.FloatField(default=20.0)),
                ('plasma_albumin', models.FloatField(default=4.0)),
                ('gut_motility_score', models.FloatField(default=1.0)),
                ('hydration_score', models.FloatField(default=1.0)),
                ('is_sick', models.BooleanField(default=False)),
                ('alcohol_last_24h', models.BooleanField(default=False)),
                ('cyp3a4_activity', models.FloatField(default=1.0)),
                ('cyp2d6_activity', models.FloatField(default=1.0)),
                ('cyp2c9_activity', models.FloatField(default=1.0)),
                ('cyp2c19_activity', models.FloatField(default=1.0)),
                ('cyp1a2_activity', models.FloatField(default=1.0)),
                ('cyp2e1_activity', models.FloatField(default=1.0)),
                ('wake_time_hr', models.FloatField(default=6.5)),
                ('sleep_time_hr', models.FloatField(default=22.5)),
                ('meal_times_hr', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'absorb_patient',
            },
        ),
        migrations.CreateModel(
            name='AbsorbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('system', 'System')], default='patient', max_length=20)),
                ('tenant', models.CharField(default='default', max_length=100)),
                ('patient_key', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'absorb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EngineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id_str', models.CharField(db_index=True, max_length=100)),
                ('tenant', models.CharField(db_index=True, default='default', max_length=100)),
                ('input_hash', models.CharField(max_length=64)),
                ('n_monte_carlo', models.IntegerField(default=100)),
                ('engine_version', models.CharField(default='1.0.0', max_length=50)),
                ('drug_db_version', models.CharField(default='1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_runs', to='core.patient')),
            ],
            options={
                'db_table': 'absorb_engine_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdherenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_id', models.CharField(blank=True, max_length=100)),
                ('drug', models.CharField(db_index=True, max_length=100)),
                ('scheduled_time', models.CharField(blank=True, max_length=50)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('skipped', 'Skipped'), ('late', 'Late')], default='taken', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_events', to='core.patient')),
            ],
            options={
                'db_table': 'absorb_adherence_event',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='PKPrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(db_index=True, max_length=100)),
                ('posterior_json', models.JSONField(default=dict)),
                ('n_observations', models.IntegerField(default=0)),
                ('engine_version', models.CharField(default='1.0.0', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_priors', to='core.patient')),
            ],
            options={
                'db_table': 'absorb_pk_prior',
                'unique_together': {('patient', 'drug_name')},
            },
        ),
    ]
