"""
Auto-generated DDI/FDI database for AbsorbAI.
Sources: OpenFDA Labels, RxNorm (NLM), OpenFDA FAERS
All free, no API key required.
Total DDI pairs: 113 | FDI pairs: 20
"""

DRUG_INTERACTIONS = [{'auc_ratio': None,
  'confidence': 0.95,
  'drug_a': 'escitalopram',
  'drug_b': 'sertraline',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.9,
  'drug_a': 'allopurinol',
  'drug_b': 'furosemide',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.9,
  'drug_a': 'allopurinol',
  'drug_b': 'hydrochlorothiazide',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.9,
  'drug_a': 'allopurinol',
  'drug_b': 'azathioprine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.9,
  'drug_a': 'tamoxifen',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.88,
  'drug_a': 'naproxen',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.88,
  'drug_a': 'celecoxib',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'losartan',
  'drug_b': 'lithium',
  'mechanism': 'Nephrotoxicity potentiation',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'losartan',
  'drug_b': 'ibuprofen',
  'mechanism': 'Nephrotoxicity potentiation',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'losartan',
  'drug_b': 'furosemide',
  'mechanism': 'Nephrotoxicity potentiation',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'spironolactone',
  'drug_b': 'digoxin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'spironolactone',
  'drug_b': 'lithium',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'spironolactone',
  'drug_b': 'ibuprofen',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'spironolactone',
  'drug_b': 'furosemide',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'lithium',
  'drug_b': 'ibuprofen',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'lithium',
  'drug_b': 'haloperidol',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'lithium',
  'drug_b': 'furosemide',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'lithium',
  'drug_b': 'metronidazole',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'clopidogrel',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'clopidogrel',
  'drug_b': 'ibuprofen',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'clopidogrel',
  'drug_b': 'morphine',
  'mechanism': 'CYP2C19 interaction',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'clopidogrel',
  'drug_b': 'sertraline',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'clopidogrel',
  'drug_b': 'venlafaxine',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'zolpidem',
  'drug_b': 'rifampin',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.82,
  'drug_a': 'zolpidem',
  'drug_b': 'morphine',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'morphine',
  'drug_b': 'diazepam',
  'faers_reports': 4293,
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label+FAERS',
  'top_reactions': ['toxicity to various agents', 'drug abuse', 'death', 'drug interaction', 'overdose']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'valproate',
  'drug_b': 'phenytoin',
  'faers_reports': 1270,
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label+FAERS',
  'top_reactions': ['drug ineffective', 'off label use', 'status epilepticus', 'seizure', 'drug interaction']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'valproate',
  'drug_b': 'carbamazepine',
  'faers_reports': 1266,
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA label+FAERS',
  'top_reactions': ['drug ineffective', 'seizure', 'off label use', 'epilepsy', 'drug interaction']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'warfarin',
  'drug_b': 'aspirin',
  'faers_reports': 4850,
  'mechanism': 'FAERS signal: dyspnoea',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['dyspnoea', 'international normalised ratio increased', 'fatigue', 'dizziness', 'nausea']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'warfarin',
  'drug_b': 'ibuprofen',
  'faers_reports': 762,
  'mechanism': 'FAERS signal: chronic kidney disease',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['chronic kidney disease',
                    'international normalised ratio increased',
                    'renal failure',
                    'acute kidney injury',
                    'dyspnoea']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'warfarin',
  'drug_b': 'fluconazole',
  'faers_reports': 653,
  'mechanism': 'FAERS signal: drug interaction',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['drug interaction',
                    'international normalised ratio increased',
                    'chronic kidney disease',
                    'renal failure',
                    'acute kidney injury']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'warfarin',
  'drug_b': 'amiodarone',
  'faers_reports': 2314,
  'mechanism': 'FAERS signal: dyspnoea',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['dyspnoea',
                    'nausea',
                    'atrial fibrillation',
                    'international normalised ratio increased',
                    'drug interaction']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'warfarin',
  'drug_b': 'clarithromycin',
  'faers_reports': 669,
  'mechanism': 'FAERS signal: drug interaction',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['drug interaction',
                    'international normalised ratio increased',
                    'acute kidney injury',
                    'dyspnoea',
                    'toxicity to various agents']},
 {'auc_ratio': None,
  'confidence': 0.8,
  'drug_a': 'fluoxetine',
  'drug_b': 'tramadol',
  'faers_reports': 2597,
  'mechanism': 'FAERS signal: acute kidney injury',
  'onset_hours': None,
  'severity': 'high',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['acute kidney injury',
                    'headache',
                    'drug interaction',
                    'chronic kidney disease',
                    'serotonin syndrome']},
 {'auc_ratio': None,
  'confidence': 0.75,
  'drug_a': 'glipizide',
  'drug_b': 'ibuprofen',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.75,
  'drug_a': 'olanzapine',
  'drug_b': 'carbamazepine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.75,
  'drug_a': 'olanzapine',
  'drug_b': 'diazepam',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.75,
  'drug_a': 'olanzapine',
  'drug_b': 'fluoxetine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.75,
  'drug_a': 'olanzapine',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.7,
  'drug_a': 'levodopa_carbidopa',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.7,
  'drug_a': 'warfarin',
  'drug_b': 'metronidazole',
  'faers_reports': 1397,
  'mechanism': 'FAERS signal: nausea',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['nausea', 'abdominal pain', 'sepsis', 'vomiting', 'abdominal distension']},
 {'auc_ratio': None,
  'confidence': 0.7,
  'drug_a': 'digoxin',
  'drug_b': 'amiodarone',
  'faers_reports': 2086,
  'mechanism': 'FAERS signal: atrial fibrillation',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['atrial fibrillation', 'dyspnoea', 'dizziness', 'cardiac failure congestive', 'fatigue']},
 {'auc_ratio': None,
  'confidence': 0.7,
  'drug_a': 'lithium',
  'drug_b': 'lisinopril',
  'faers_reports': 607,
  'mechanism': 'FAERS signal: toxicity to various agents',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['toxicity to various agents', 'tremor', 'acute kidney injury', 'drug interaction', 'nausea']},
 {'auc_ratio': None,
  'confidence': 0.7,
  'drug_a': 'sertraline',
  'drug_b': 'tramadol',
  'faers_reports': 2837,
  'mechanism': 'FAERS signal: headache',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['headache', 'fatigue', 'diarrhoea', 'nausea', 'fall']},
 {'auc_ratio': None,
  'confidence': 0.7,
  'drug_a': 'atorvastatin',
  'drug_b': 'clarithromycin',
  'faers_reports': 2532,
  'mechanism': 'FAERS signal: drug ineffective',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA FAERS',
  'top_reactions': ['drug ineffective', 'macular degeneration', 'malaise', 'nausea', 'pyrexia']},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'amlodipine',
  'drug_b': 'atorvastatin',
  'mechanism': 'CYP3A interaction',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'amlodipine',
  'drug_b': 'simvastatin',
  'mechanism': 'CYP3A interaction',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'simvastatin',
  'drug_b': 'atorvastatin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'simvastatin',
  'drug_b': 'digoxin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'rosuvastatin',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'rosuvastatin',
  'drug_b': 'atorvastatin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'azithromycin',
  'drug_b': 'warfarin',
  'mechanism': 'Hepatotoxicity potentiation',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'ondansetron',
  'drug_b': 'sertraline',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.65,
  'drug_a': 'ondansetron',
  'drug_b': 'venlafaxine',
  'mechanism': 'Serotonin syndrome risk',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.6,
  'drug_a': 'alendronate',
  'drug_b': 'aspirin',
  'mechanism': 'Absorption interference',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.6,
  'drug_a': 'tamsulosin',
  'drug_b': 'ketoconazole',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'lisinopril',
  'drug_b': 'furosemide',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'carvedilol',
  'drug_b': 'rifampin',
  'mechanism': 'CYPP450 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'amiodarone',
  'drug_b': 'lithium',
  'mechanism': 'QT prolongation',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'hydrochlorothiazide',
  'drug_b': 'lisinopril',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'hydrochlorothiazide',
  'drug_b': 'furosemide',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'pravastatin',
  'drug_b': 'cyclosporine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'metformin',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'sitagliptin',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'empagliflozin',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'insulin_glargine',
  'drug_b': 'fluoxetine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'insulin_glargine',
  'drug_b': 'lisinopril',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'ciprofloxacin',
  'drug_b': 'theophylline',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'alprazolam',
  'drug_b': 'digoxin',
  'mechanism': 'CYP3A interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'alprazolam',
  'drug_b': 'morphine',
  'mechanism': 'CYP3A interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'montelukast',
  'drug_b': 'warfarin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'montelukast',
  'drug_b': 'digoxin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'montelukast',
  'drug_b': 'itraconazole',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'montelukast',
  'drug_b': 'theophylline',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'quetiapine',
  'drug_b': 'ketoconazole',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'risperidone',
  'drug_b': 'carbamazepine',
  'mechanism': 'CYP2D6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'risperidone',
  'drug_b': 'losartan',
  'mechanism': 'CYP2D6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'clozapine',
  'drug_b': 'ciprofloxacin',
  'mechanism': 'CYP1A2 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'carbamazepine',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'valproate',
  'drug_b': 'rifampin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'valproate',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'insulin_aspart',
  'drug_b': 'fluoxetine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'insulin_aspart',
  'drug_b': 'lisinopril',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'finasteride',
  'drug_b': 'warfarin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'finasteride',
  'drug_b': 'digoxin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'finasteride',
  'drug_b': 'theophylline',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'bupropion',
  'drug_b': 'phenytoin',
  'mechanism': 'CYP2B6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'bupropion',
  'drug_b': 'carbamazepine',
  'mechanism': 'CYP2B6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.5,
  'drug_a': 'bupropion',
  'drug_b': 'losartan',
  'mechanism': 'CYP2B6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'heparin',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'enalapril',
  'drug_b': 'lisinopril',
  'mechanism': 'Nephrotoxicity potentiation',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'enalapril',
  'drug_b': 'losartan',
  'mechanism': 'Nephrotoxicity potentiation',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'metoprolol',
  'drug_b': 'verapamil',
  'mechanism': 'CYP2D6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'metoprolol',
  'drug_b': 'diltiazem',
  'mechanism': 'CYP2D6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'atenolol',
  'drug_b': 'amlodipine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'carvedilol',
  'drug_b': 'digoxin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'carvedilol',
  'drug_b': 'cyclosporine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'atorvastatin',
  'drug_b': 'rifampin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'ciprofloxacin',
  'drug_b': 'warfarin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'sertraline',
  'drug_b': 'warfarin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'montelukast',
  'drug_b': 'ibuprofen',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'montelukast',
  'drug_b': 'diazepam',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'montelukast',
  'drug_b': 'levothyroxine',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'fentanyl',
  'drug_b': 'morphine',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'oxycodone',
  'drug_b': 'morphine',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'quetiapine',
  'drug_b': 'phenytoin',
  'mechanism': 'CYP3A4 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'risperidone',
  'drug_b': 'fluoxetine',
  'mechanism': 'CYP2D6 interaction',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'meropenem',
  'drug_b': 'valproate',
  'mechanism': 'Nephrotoxicity potentiation',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'meropenem',
  'drug_b': 'losartan',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'insulin_aspart',
  'drug_b': 'atorvastatin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'levodopa_carbidopa',
  'drug_b': 'phenytoin',
  'mechanism': 'See FDA label',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'enoxaparin',
  'drug_b': 'aspirin',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'auc_ratio': None,
  'confidence': 0.4,
  'drug_a': 'enoxaparin',
  'drug_b': 'ibuprofen',
  'mechanism': 'Increased bleeding risk',
  'onset_hours': None,
  'severity': 'low',
  'source': 'OpenFDA label'}]

FOOD_DRUG_INTERACTIONS = [{'confidence': 0.82,
  'drug': 'losartan',
  'food': 'vitamin_k',
  'mechanism': 'Competitive antagonism of anticoagulant effect',
  'separation_hrs': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'confidence': 0.82,
  'drug': 'spironolactone',
  'food': 'vitamin_k',
  'mechanism': 'Competitive antagonism of anticoagulant effect',
  'separation_hrs': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'confidence': 0.82,
  'drug': 'spironolactone',
  'food': 'iron',
  'mechanism': 'Chelation complex formation (Fe2+/Fe3+)',
  'separation_hrs': 2,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'confidence': 0.82,
  'drug': 'zolpidem',
  'food': 'alcohol',
  'mechanism': 'CYP induction/inhibition + CNS/hepatic effect',
  'separation_hrs': None,
  'severity': 'high',
  'source': 'OpenFDA label'},
 {'confidence': 0.75,
  'drug': 'olanzapine',
  'food': 'alcohol',
  'mechanism': 'CYP induction/inhibition + CNS/hepatic effect',
  'separation_hrs': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'enalapril',
  'food': 'vitamin_k',
  'mechanism': 'Competitive antagonism of anticoagulant effect',
  'separation_hrs': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'atenolol',
  'food': 'dairy',
  'mechanism': 'Chelation complex formation (Ca2+)',
  'separation_hrs': 2,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'spironolactone',
  'food': 'tyramine',
  'mechanism': 'MAO inhibition → hypertensive crisis risk',
  'separation_hrs': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'rosuvastatin',
  'food': 'antacid',
  'mechanism': 'pH-dependent absorption reduction',
  'separation_hrs': 2,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'ciprofloxacin',
  'food': 'caffeine',
  'mechanism': 'CYP1A2 substrate competition / CNS effect',
  'separation_hrs': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'morphine',
  'food': 'alcohol',
  'mechanism': 'CYP induction/inhibition + CNS/hepatic effect',
  'separation_hrs': None,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.65,
  'drug': 'levodopa_carbidopa',
  'food': 'iron',
  'mechanism': 'Chelation complex formation (Fe2+/Fe3+)',
  'separation_hrs': 2,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.6,
  'drug': 'alendronate',
  'food': 'dairy',
  'mechanism': 'Chelation complex formation (Ca2+)',
  'separation_hrs': 2,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.6,
  'drug': 'alendronate',
  'food': 'antacid',
  'mechanism': 'pH-dependent absorption reduction',
  'separation_hrs': 2,
  'severity': 'moderate',
  'source': 'OpenFDA label'},
 {'confidence': 0.5,
  'drug': 'atorvastatin',
  'food': 'grapefruit',
  'mechanism': 'CYP3A4 inhibition by furanocoumarins',
  'separation_hrs': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'confidence': 0.5,
  'drug': 'atorvastatin',
  'food': 'dairy',
  'mechanism': 'Chelation complex formation (Ca2+)',
  'separation_hrs': 2,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'confidence': 0.5,
  'drug': 'simvastatin',
  'food': 'grapefruit',
  'mechanism': 'CYP3A4 inhibition by furanocoumarins',
  'separation_hrs': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'confidence': 0.5,
  'drug': 'metronidazole',
  'food': 'alcohol',
  'mechanism': 'CYP induction/inhibition + CNS/hepatic effect',
  'separation_hrs': None,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'confidence': 0.5,
  'drug': 'calcium_carbonate',
  'food': 'antacid',
  'mechanism': 'pH-dependent absorption reduction',
  'separation_hrs': 2,
  'severity': 'low',
  'source': 'OpenFDA label'},
 {'confidence': 0.5,
  'drug': 'venlafaxine',
  'food': 'alcohol',
  'mechanism': 'CYP induction/inhibition + CNS/hepatic effect',
  'separation_hrs': None,
  'severity': 'low',
  'source': 'OpenFDA label'}]

_DDI_COUNT = 113
_FDI_COUNT = 20
_SOURCES = ["OpenFDA Labels", "RxNorm (NLM)", "OpenFDA FAERS"]
