"""
Main engine orchestrator: ties all 10 layers together.
Single entry point for the Django API views.
"""
import json
import datetime
from typing import Dict, List, Optional, Any

from .biological_twin import PatientPhysiology, personalize_pk
from .pk_pd_engine import (
    DosingEvent, simulate_pk_pd, DRUG_PD_PARAMS,
    compute_drug_interaction_pk
)
from .uncertainty_engine import run_monte_carlo, BayesianParameterUpdater
from .knowledge_graph import PharmacologicalKnowledgeGraph, compute_enzyme_inhibition_time_course
from .optimizer import (
    MedicationConstraint, PatientPreferences, compute_pareto_frontier, ScheduleSolution
)
from .adversarial_engine import run_stress_test, STANDARD_STRESS_SCENARIOS
from .explainability import (
    ReasoningChain, AuditLog, check_hard_safety_rails,
    build_interaction_reasoning_chain, build_schedule_reasoning_chain,
    GLOBAL_AUDIT_LOG
)
from .gemma_engine import (
    generate_patient_explanation,
    generate_doctor_prescription_suggestions,
    generate_risk_summary_narrative,
)
from .input_validator import validate_and_sanitize, confidence_to_uncertainty_scale


CLINICAL_DISCLAIMER = (
    "FOR DECISION SUPPORT ONLY. This output is generated by a computational model "
    "and does not constitute medical advice, diagnosis, or treatment. All clinical "
    "decisions must be made by a licensed healthcare professional. AbsorbAI assumes "
    "no liability for outcomes resulting from use of this tool."
)

# Global KG instance (built once at startup)
KNOWLEDGE_GRAPH = PharmacologicalKnowledgeGraph()

# Per-patient Bayesian updaters
_PATIENT_UPDATERS: Dict[str, Dict[str, BayesianParameterUpdater]] = {}


def _build_patient_physiology(profile: Dict) -> PatientPhysiology:
    return PatientPhysiology(
        age=float(profile.get('age', 45)),
        weight=float(profile.get('weight', 70)),
        height=float(profile.get('height', 170)),
        sex=profile.get('sex', 'M'),
        serum_creatinine=float(profile.get('serum_creatinine', 1.0)),
        child_pugh_score=int(profile.get('child_pugh_score', 5)),
        body_fat_pct=float(profile.get('body_fat_pct', 20.0)),
        plasma_albumin=float(profile.get('plasma_albumin', 4.0)),
        gut_motility_score=float(profile.get('gut_motility_score', 1.0)),
        hydration_score=float(profile.get('hydration_score', 1.0)),
        is_sick=bool(profile.get('is_sick', False)),
        alcohol_last_24h=bool(profile.get('alcohol_last_24h', False)),
        cyp3a4_activity=float(profile.get('cyp3a4_activity', 1.0)),
        cyp2d6_activity=float(profile.get('cyp2d6_activity', 1.0)),
        cyp2c9_activity=float(profile.get('cyp2c9_activity', 1.0)),
        cyp2c19_activity=float(profile.get('cyp2c19_activity', 1.0)),
        cyp1a2_activity=float(profile.get('cyp1a2_activity', 1.0)),
        cyp2e1_activity=float(profile.get('cyp2e1_activity', 1.0)),
    )


def _build_dosing_events(rx: Dict) -> List[DosingEvent]:
    """Convert prescription dict to DosingEvent list over 72 hours"""
    freq = rx.get('frequency_per_day', 1)
    dose_mg = float(rx.get('dose_mg', 100))
    start_hr = float(rx.get('start_time_hr', 8.0))
    f = float(rx.get('bioavailability', 0.8))
    interval = 24.0 / max(freq, 1)
    events = []
    for day in range(3):
        for i in range(freq):
            t = day * 24 + start_hr + i * interval
            events.append(DosingEvent(time_hr=t, dose_mg=dose_mg, bioavailability=f))
    return events


def analyze_patient_regimen(
    patient_id: str,
    patient_profile: Dict,
    prescriptions: List[Dict],
    dietary_factors: List[str] = None,
    n_monte_carlo: int = 500,
) -> Dict:
    """
    Full 10-layer analysis of a patient's medication regimen.
    Returns comprehensive result dict for the API.
    """
    if dietary_factors is None:
        dietary_factors = []

    # ── Input validation + data quality gate ──────────────────────────────────
    validation = validate_and_sanitize(patient_profile, prescriptions)
    if not validation.is_safe_to_simulate:
        return {
            'patient_id': patient_id,
            'timestamp': datetime.datetime.utcnow().isoformat(),
            'decision_support_only': True,
            'disclaimer': CLINICAL_DISCLAIMER,
            'validation': validation.to_dict(),
            'error': 'Input validation failed — cannot simulate safely',
            'errors': validation.errors,
        }

    # Use cleaned, clamped inputs from here on
    patient_profile = validation.cleaned_profile
    prescriptions   = validation.cleaned_prescriptions

    # Scale MC samples by data quality (low confidence → more samples for wider dist)
    n_monte_carlo = max(50, int(n_monte_carlo * validation.mc_multiplier))

    # Uncertainty scale factor — widen PK stds when inputs are uncertain
    _unc_scale = confidence_to_uncertainty_scale(validation.data_confidence)

    patient = _build_patient_physiology(patient_profile)
    drug_names = [rx.get('drug_name', '') for rx in prescriptions]

    # ── Layer 10: Hard safety rails (checked FIRST, before any computation) ──
    daily_doses = {
        rx['drug_name'].lower(): float(rx.get('dose_mg', 0)) * rx.get('frequency_per_day', 1)
        for rx in prescriptions if rx.get('drug_name')
    }
    safety_violations = check_hard_safety_rails(drug_names, daily_doses)

    # ── Layer 5: Knowledge graph interactions ──
    kg_interactions = KNOWLEDGE_GRAPH.query_drug_interactions_for_regimen(
        drug_names, dietary_factors
    )
    counterfactual = KNOWLEDGE_GRAPH.counterfactual_risk_contribution(drug_names)

    # ── Layers 1-3: Per-drug PK/PD + Monte Carlo ──
    pk_results = {}
    mc_results = {}

    for rx in prescriptions:
        drug = rx.get('drug_name', '')
        if not drug:
            continue

        # Build concurrent inhibitor context from KG
        concurrent_inhibitors = {}
        for itx in kg_interactions:
            if itx.get('entity_b', '').lower() in (drug.lower(), f"{drug.lower()}_absorption"):
                mech = itx.get('mechanism', '')
                if 'cyp3a4' in mech.lower() or 'CYP3A4' in itx.get('path', []):
                    concurrent_inhibitors['cyp3a4'] = min(itx.get('magnitude', 0) * 0.5, 0.8)

        # Layer 1: Personalized PK
        pk_params = personalize_pk(drug, patient, patient_id, concurrent_inhibitors)

        # Widen std deviations proportionally to data uncertainty
        if _unc_scale > 1.0:
            pk_params.cl_std          *= _unc_scale
            pk_params.vd_central_std  *= _unc_scale
            pk_params.vd_peripheral_std *= _unc_scale
            pk_params.f_std           *= _unc_scale
            pk_params.ka_std          *= _unc_scale
            pk_params.q_std           *= _unc_scale

        # Get/create Bayesian updater
        if patient_id not in _PATIENT_UPDATERS:
            _PATIENT_UPDATERS[patient_id] = {}
        if drug.lower() not in _PATIENT_UPDATERS[patient_id]:
            _PATIENT_UPDATERS[patient_id][drug.lower()] = BayesianParameterUpdater(pk_params)
        else:
            # Use Bayesian-updated params if available
            pk_params = _PATIENT_UPDATERS[patient_id][drug.lower()].get_updated_pk()

        # Layer 2: PK/PD simulation
        pd = DRUG_PD_PARAMS.get(drug.lower())
        dosing_events = _build_dosing_events(rx)

        try:
            sim_result = simulate_pk_pd(pk_params, pd, dosing_events, t_end=72.0, dt=0.5)
        except Exception as e:
            sim_result = None

        # Layer 3: Monte Carlo uncertainty
        toxic_threshold = None  # could be drug-specific
        try:
            mc_result = run_monte_carlo(
                pk_params, dosing_events, drug,
                n_sims=n_monte_carlo, t_end=72.0, dt=0.5,
                seed=hash(patient_id + drug) % 2**31,
            )
        except Exception:
            mc_result = None

        pk_results[drug] = {
            'pk_params': {
                'half_life_mean': round(pk_params.half_life_mean, 2),
                'half_life_std': round(pk_params.half_life_std, 2),
                'cl_mean': round(pk_params.cl_mean, 3),
                'cl_std': round(pk_params.cl_std, 3),
                'vd_central_mean': round(pk_params.vd_central_mean, 2),
                'f_mean': round(pk_params.f_mean, 3),
                'crcl': round(patient.creatinine_clearance(), 1),
            },
            'simulation': {
                'auc': round(sim_result.auc, 3) if sim_result else None,
                'cmax': round(sim_result.cmax, 4) if sim_result else None,
                'tmax': round(sim_result.tmax, 2) if sim_result else None,
                't_above_ec50': round(sim_result.t_above_ec50, 2) if sim_result else None,
                'concentration_timeline': {
                    't': sim_result.times[:144:2].tolist() if sim_result else [],
                    'c': sim_result.c_central[:144:2].tolist() if sim_result else [],
                    'effect': sim_result.effect[:144:2].tolist() if sim_result else [],
                } if sim_result else {},
            },
            'uncertainty': mc_result.auc_distribution.to_dict() if mc_result else {},
            'mc_cmax': mc_result.cmax_distribution.to_dict() if mc_result else {},
            'concentration_bands': mc_result.concentration_timeline if mc_result else {},
            'efficacy_probability': round(mc_result.efficacy_probability, 3) if mc_result else None,
        }
        mc_results[drug] = mc_result

    # ── Layer 4: Schedule optimizer ──
    med_constraints = []
    for rx in prescriptions:
        drug = rx.get('drug_name', '')
        if not drug:
            continue
        drug_lower = drug.lower()
        from .explainability import MAX_SAFE_DOSES
        med_constraints.append(MedicationConstraint(
            drug_name=drug,
            dose_mg=float(rx.get('dose_mg', 100)),
            frequency_per_day=int(rx.get('frequency_per_day', 1)),
            min_interval_hrs=24.0 / max(int(rx.get('frequency_per_day', 1)), 1) * 0.5,
            max_daily_dose_mg=MAX_SAFE_DOSES.get(drug_lower, 9999),
            must_take_with_food=rx.get('with_food', False),
            must_take_empty_stomach=rx.get('empty_stomach', False),
        ))

    prefs = PatientPreferences(
        wake_time_hr=float(patient_profile.get('wake_time_hr', 7.0)),
        sleep_time_hr=float(patient_profile.get('sleep_time_hr', 23.0)),
        meal_times_hr=patient_profile.get('meal_times_hr', [7.5, 13.0, 19.5]),
    )

    # Build interaction matrix for optimizer
    interaction_matrix = {}
    for itx in kg_interactions:
        a = itx.get('entity_a', '')
        b = itx.get('entity_b', '').replace('_absorption', '').replace('_exposure', '').replace('_anticoagulation', '')
        sev = itx.get('severity', 0.0)
        if a and b:
            interaction_matrix[(a, b)] = max(interaction_matrix.get((a, b), 0), sev)
            interaction_matrix[(b, a)] = max(interaction_matrix.get((b, a), 0), sev)

    # PK summaries for optimizer
    pk_summaries = {}
    for drug, pk_data in pk_results.items():
        sim = pk_data.get('simulation', {})
        mc_unc = pk_data.get('uncertainty', {})
        pk_summaries[drug] = {
            'therapeutic_coverage': pk_data.get('efficacy_probability', 0.7) or 0.7,
            'peak_risk': min((sim.get('cmax', 0) or 0) / 10.0, 1.0),
        }

    try:
        pareto_solutions = compute_pareto_frontier(
            med_constraints, prefs, interaction_matrix, pk_summaries,
            n_candidate_schedules=100,
        )
    except Exception:
        pareto_solutions = []

    # Serialize Pareto solutions
    pareto_serialized = []
    for sol in pareto_solutions[:5]:
        pareto_serialized.append({
            'label': sol.label or 'Optimal Schedule',
            'is_feasible': sol.is_feasible,
            'objectives': {k: round(v, 4) for k, v in sol.objectives.items()},
            'violations': sol.violated_constraints[:3],
            'doses': [
                {
                    'drug': d.drug_name,
                    'dose_mg': d.dose_mg,
                    'time_hr': round(d.time_hr, 2),
                    'day': d.day,
                    'with_food': d.with_food,
                    'rationale': d.rationale,
                }
                for d in sol.doses[:20]  # limit output size
            ],
        })

    # ── Layer 7: Adversarial stress testing ──
    stress_results_all = {}
    for rx in prescriptions[:3]:  # test top 3 drugs
        drug = rx.get('drug_name', '')
        if not drug or drug.lower() not in [k.lower() for k in pk_results.keys()]:
            continue
        try:
            pk_p = personalize_pk(drug, patient, patient_id)
            dosing_ev = _build_dosing_events(rx)
            stress_results, is_fragile, recommendation = run_stress_test(
                drug, pk_p, patient, dosing_ev,
                scenarios=STANDARD_STRESS_SCENARIOS[:5],
            )
            stress_results_all[drug] = {
                'is_fragile': is_fragile,
                'recommendation': recommendation,
                'scenarios': [
                    {
                        'name': r.scenario.name,
                        'description': r.scenario.description,
                        'outcome_severity': round(r.outcome_severity, 3),
                        'outcome': r.outcome_description,
                        'is_catastrophic': r.is_catastrophic,
                        'mitigation': r.mitigation_suggestion,
                        'pk_change_pct': r.pk_change_pct,
                    }
                    for r in stress_results
                ],
            }
        except Exception:
            pass

    # ── Layer 5: KG interaction reasoning chains ──
    interaction_chains = []
    for itx in kg_interactions[:8]:
        a = itx.get('entity_a', '')
        b = itx.get('entity_b', '')
        pk_a = pk_results.get(a, {}).get('pk_params', {})
        pk_b = pk_results.get(b, {}).get('pk_params', {})
        chain = build_interaction_reasoning_chain(a, b, itx, pk_a, pk_b)
        interaction_chains.append({
            'entity_a': a,
            'entity_b': b,
            'severity': round(itx.get('severity', 0), 3),
            'confidence': round(itx.get('confidence', 0), 3),
            'mechanism': itx.get('mechanism', ''),
            'direction': itx.get('direction', ''),
            'magnitude': itx.get('magnitude', 0),
            'magnitude_unit': itx.get('magnitude_unit', ''),
            'references': itx.get('references', []),
            'onset_hours': itx.get('onset_hours', 1),
            'offset_hours': itx.get('offset_hours', 24),
            'is_irreversible': itx.get('is_irreversible', False),
            'reasoning_chain': chain.to_plain_english(),
            'reasoning_dict': chain.to_dict(),
        })

    # ── Layer 9: Counterfactual reasoning ──
    counterfactual_serialized = {
        drug: pct for drug, pct in counterfactual.items()
        if abs(pct) > 0.5
    }

    # ── Layer 8: Uncertainty reduction report ──
    uncertainty_reductions = {}
    if patient_id in _PATIENT_UPDATERS:
        for drug, updater in _PATIENT_UPDATERS[patient_id].items():
            uncertainty_reductions[drug] = updater.uncertainty_reduction_pct()

    # ── Risk summary via Gemma ──
    high_count = sum(1 for itx in kg_interactions if itx.get('severity', 0) > 0.6)
    mod_count = sum(1 for itx in kg_interactions if 0.3 < itx.get('severity', 0) <= 0.6)
    top_driver = max(counterfactual_serialized.items(),
                     key=lambda x: abs(x[1]), default=('N/A', 0))[0] if counterfactual_serialized else 'N/A'

    risk_summary = generate_risk_summary_narrative(
        {'high_count': high_count, 'mod_count': mod_count, 'primary_driver': top_driver},
        patient_profile.get('name', 'Patient'),
        [itx.get('reasoning_chain', '') for itx in interaction_chains[:3]],
    )

    # ── Layer 10: Audit log ──
    entry_id = GLOBAL_AUDIT_LOG.log_recommendation(
        recommendation_type='regimen_analysis',
        patient_id=patient_id,
        input_state={
            'drug_count': len(prescriptions),
            'patient_age': patient.age,
            'crcl': round(patient.creatinine_clearance(), 1),
        },
        output={
            'high_risk_interactions': high_count,
            'moderate_risk_interactions': mod_count,
            'pareto_solutions_count': len(pareto_solutions),
        },
        reasoning_chain=None,
    )

    return {
        'patient_id': patient_id,
        'timestamp': datetime.datetime.utcnow().isoformat(),
        'decision_support_only': True,
        'disclaimer': CLINICAL_DISCLAIMER,
        'data_quality': {
            'confidence': round(validation.data_confidence, 3),
            'mc_multiplier': round(validation.mc_multiplier, 2),
            'warnings': validation.warnings,
            'unc_scale': round(_unc_scale, 2),
        },
        'audit_entry_id': entry_id,
        'safety_violations': safety_violations,
        'has_fatal_violations': any(v['severity'] == 'FATAL' for v in safety_violations),
        'pk_results': pk_results,
        'interaction_chains': interaction_chains,
        'counterfactual_risk': counterfactual_serialized,
        'pareto_schedules': pareto_serialized,
        'stress_test_results': stress_results_all,
        'uncertainty_reductions': uncertainty_reductions,
        'risk_summary': risk_summary,
        'patient_physiology': {
            'crcl': round(patient.creatinine_clearance(), 1),
            'hepatic_factor': round(patient.hepatic_function_factor(), 2),
            'bmi': round(patient.bmi(), 1),
            'ibw': round(patient.ibw(), 1),
        },
    }


def update_patient_observation(
    patient_id: str,
    drug_name: str,
    observation_type: str,
    observed_value: float,
    predicted_value: float = None,
    lab_name: str = None,
    lab_unit: str = None,
) -> Dict:
    """
    Layer 8: Update patient's Bayesian parameter estimates from new observations.
    """
    if patient_id not in _PATIENT_UPDATERS or drug_name.lower() not in _PATIENT_UPDATERS[patient_id]:
        return {'success': False, 'message': 'No prior analysis found for patient/drug'}

    updater = _PATIENT_UPDATERS[patient_id][drug_name.lower()]

    if observation_type == 'concentration' and predicted_value is not None:
        updater.update_from_concentration(
            observed_value, predicted_value,
            prediction_uncertainty=predicted_value * 0.3
        )
    elif observation_type == 'side_effect' and predicted_value is not None:
        updater.update_from_side_effect(drug_name, observed_value, predicted_value)
    elif observation_type == 'lab' and lab_name:
        updater.update_from_lab(lab_name, observed_value, lab_unit or '')

    reductions = updater.uncertainty_reduction_pct()
    return {
        'success': True,
        'uncertainty_reductions': reductions,
        'message': f'Parameters updated for {drug_name}',
    }


def get_prescription_suggestions(
    patient_id: str,
    diagnosis: str,
    current_drugs: List[str],
    patient_profile: Dict,
) -> List[Dict]:
    """Layer 8 + Gemma: get grounded prescription suggestions"""
    return generate_doctor_prescription_suggestions(
        diagnosis, current_drugs, patient_profile, KNOWLEDGE_GRAPH
    )
